<a href="https://colab.research.google.com/github/Shushukang/NLP/blob/main/%EC%8B%A4%EC%8A%B501.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 정리

## 넘파이 배열 생성

In [ ]:
# 필요한 라이브러리 임폴트
import numpy as np

In [ ]:
# 데이터 → 파이썬 리스트 자료형으로 저장
list_data1 = [1, 2, 3]
list_data2 = [4, 5, 6]
print(f'첫 번째로 생성된 리스트 자료형 데이터 : {list_data1}')

print('-'*80)

# 파이썬 리스트 자료형 덧셈 연산 실행 → 리스트의 연결(extenssion:확장의 개념)
result = list_data1 + list_data2
print(f'파이썬 자료형 데이터에 대한 덧셈 연산의 결과 : \n{result}')

print('-'*80)

# 파이썬 리스트 자료형 → 넘파이 배열로 변환
arr1 = np.array(list_data1)
arr2 = np.array(list_data2)
print(f'첫 번째로 생성된 넘파이 배열 데이터 : {arr1}')

print('-'*80)

# 넘파이 배열 덧셈 연산 실행
result = arr1 + arr2
print(f'넘파이 자료형 데이터에 대한 덧셈 연산의 결과 : {result}')

첫 번째로 생성된 리스트 자료형 데이터 : [1, 2, 3]
--------------------------------------------------------------------------------
파이썬 자료형 데이터에 대한 덧셈 연산의 결과 : 
[1, 2, 3, 4, 5, 6]
--------------------------------------------------------------------------------
첫 번째로 생성된 넘파이 배열 데이터 : [1 2 3]
--------------------------------------------------------------------------------
넘파이 자료형 데이터에 대한 덧셈 연산의 결과 : [5 7 9]


In [ ]:
### np.arange(start, stop, step) : 연속적으로 증가하거나 감소하는 배열 생성
arr = np.arange(start=1, stop=15, step=2)
print(f'생성된 배열 : {arr}')

생성된 배열 : [ 1  3  5  7  9 11 13]


## reshape()

In [ ]:
# 구조 변경 전 데이터 생성
arr1 = np.arange(0, 24, 1)
print(f'1차원 배열 생성 : \n{arr1}')

print('-'*80)

# 1차원 배열 → 2차원 배열로 변환 → 모양 (4,6)
arr2 = arr1.reshape((4,6))
# np.reshape(arr, (4,6))
print(f'1차원 배열을 2차원 배열로 변환한 결과 : \n{arr2}')

print('-'*80)

# 1차원 배열 → 3차원 배열로 변환 → 모양 (4,3,2)
arr3 = arr1.reshape((4, 3, 2))
print(f'1차원 배열을 3차원 배열로 변환한 결과 : \n{arr3}')

print('-'*80)

# 2차원 배열 → 3차원 배열로 변환 → 모양 (4,3,2)
arr4 = arr2.reshape(4,3,2)
print(f'2차원 배열을 3차원 배열로 변환한 결과 : \n{arr4}')

# 3차원 → 2차원 가능함

1차원 배열 생성 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
--------------------------------------------------------------------------------
1차원 배열을 2차원 배열로 변환한 결과 : 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------------------------------------
1차원 배열을 3차원 배열로 변환한 결과 : 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
--------------------------------------------------------------------------------
2차원 배열을 3차원 배열로 변환한 결과 : 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


## 인덱싱

In [ ]:
### pyton list 자료형 데이터 → 인덱싱
list_data = [[1,2,3],[4,5,6]]
print(f'리스트 자료형 데이터 확인 : \n{list_data}')

print('-'*80)

# 숫자 1 추출
'''
# 파이썬 리스트 자료형 (구조 X)
1. 단계적으로 인덱싱
2. 첫 번째 성분 원소 인덱싱 → 첫 번째 성분 원소의 첫 번째 성분 원소
'''
result = list_data[0][0]
print(f'숫자 1을 인덱싱한 결과 : {result}')

리스트 자료형 데이터 확인 : 
[[1, 2, 3], [4, 5, 6]]
--------------------------------------------------------------------------------
숫자 1을 인덱싱한 결과 : 1


In [ ]:
### 2차원 넘파이 배열 → 인덱싱

# 파이썬 리스트 자료형 데이터 → 2차원 배열로 변환
arr = np.array(list_data)
print(f'넘파이 배열로 변환된 결과 확인 : \n{arr}')

print('-'*80)

# 숫자 1 추출 → 구조 이용(행, 열, 깊이)
# arr[row index, col index]
result = arr[0, 0]
# result = arr[0][0] 도 가능
print(f'숫자 1을 인덱싱한 결과 : {result}')

넘파이 배열로 변환된 결과 확인 : 
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
숫자 1을 인덱싱한 결과 : 1


In [ ]:
### 3차원 넘파이 배열 생성 → 인덱싱

# 모양(10, 10, 3) 설정 : 이미지의 구조 모방
arr1 = np.arange(300).reshape((10,10,3))
print(f'3차원 배열 확인 : \n{arr1}')

print('-'*80)

# 인덱싱 → 행 : 전체, 열 : 전체, 깊이 : 0번
arr2 = arr1[:,:,0]
# arr2 = arr[:][:][0]
print(f'0번 깊이를 인덱싱한 결과 : \n{result}')

3차원 배열 확인 : 
[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]
  [ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]]

 [[ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]]

 [[120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]
  [135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]]

 [[150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 169 170]
  [171 172 173]
  [174 175 176]
  [177 178 179]]

 [[180 181 182]

## 슬라이싱

In [ ]:
### 슬라이싱을 이용한 복사(copy)

# 3차원 배열 생성
arr1 = np.arange(300).reshape((10,10,3))
print(f'3차원 배열 확인 : \n{arr1}')

print('-'*80)

# 3차원 배열 복사
arr2 = arr1[:,:,:]
print(f'3차원 배열을 복사한 결과 : \n{arr2}')

print('-'*80)

# 복사에 대한 검증 → arr1과 arr2의 크기 비교
print(arr1 == arr2)

3차원 배열 확인 : 
[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]
  [ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]]

 [[ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]]

 [[120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]
  [135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]]

 [[150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 169 170]
  [171 172 173]
  [174 175 176]
  [177 178 179]]

 [[180 181 182]

# pandas 정리

In [ ]:
# 필요한 라이브러리 임폴트
import pandas as pd

## DataFrame 생성

In [ ]:
### 파이썬 dict 자료형 데이터 → DataFrame으로 변환

# 파이썬 딕셔너리 자료형 데이터 생성
pop_dict = {'2022':[9436836, 3317812, 2964820, 2365619],
            '2015':[9904312, 3448737, 2890451, 2466052],
            '2010':[9631482, 3393191, 2632035, 2431774]}

# pd.DataFrame(data)
df = pd.DataFrame(pop_dict)
print(f'수집된 DataFrame 자료형 데이터 확인 : \n{df}')

수집된 DataFrame 자료형 데이터 확인 : 
      2022     2015     2010
0  9436836  9904312  9631482
1  3317812  3448737  3393191
2  2964820  2890451  2632035
3  2365619  2466052  2431774


In [ ]:
### csv 파일 → DataFrame으로 변환

# 파일 경로 설정
file_path = '/content/drive/MyDrive/딥러닝/dataframe.csv'

# pd.read_csv()
df1 = pd.read_csv(file_path)

# 결과 확인하기
print(df1)

                                              sentence  label
0    본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
1    본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...      1
2    본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...      1
3    아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...      1
4    본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...      1
..                                                 ...    ...
145  본 발명은 엉겅퀴(Cirsium japonicum var. ussuriense) 잎...      1
146  본 발명은 어성초 초임계 추출물을 유효성분으로 함유하는 관절염 질환의 예방 및 치료...      1
147  본 발명은 항염증 활성과 파골세포 억제 효과를 갖는 두충 추출물, 상기 추출물을 유...      1
148  본 발명은 유효성분으로서 다음과 같은 진세노사이드 함량을 나타내는 홍삼 발효액을 포...      1
149  본 발명은 전통 한의약 이론에 근거하여 한방의 복합 생약추출물에 발효기술을 이용하여...      1

[150 rows x 2 columns]


In [ ]:
### tsv 파일 → DataFrame으로 변환

# 파일 경로 설정
file_path = '/content/drive/MyDrive/딥러닝/ratings_train.tsv'
# file_path = '/content/drive/MyDrive/딥러닝/ratings_train.txt'도 가능
# text 파일이어도 tab으로 구분되는 표 형식의 파일이라면 read_csv로 인식 가능
# 한글 파일(알파벳이어도 영어가 아닌 언어)은 인코딩 형식이 UTF-8로 저장되어야 함 (인식이 안 될 경우 다른 이름으로 저장하기)

# pd.read_csv(sep='\t')
df2 = pd.read_csv(file_path, sep='\t')

# 결과 확인하기
print(df2)

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]


## DataFrame - 속성 변수

In [ ]:
# 컬럼 이름 → 컬럼 인덱스 추출
info_cols = df2.columns
print(f'컬럼 인덱스 확인 : \n{info_cols}')

print('-'*80)

# 컬럼 이름 → 인덱싱 → 특정 컬럼 이름 추출
col1 = info_cols[0]
print(f'첫 번째 컬럼의 이름 : {col1}')

print('-'*80)

# 행 인덱스 추출
info_idx = df2.index
print(f'행 인덱스 확인 : {info_idx}')

print('-'*80)

# values 추출
info_vals = df2.values
print(f'값(데이터) 추출 : \n{info_vals}')

print('-'*80)

# shape(구조, 모양) 출력
info_shape = df2.shape
print(f'데이터프레임의 모양(구조) 확인 : {info_shape}')

print('-'*80)

# size(성분 원소의 개수) 출력
info_size = df2.size
print(f'데이터프레임의 성분 원소 개수 확인 : {info_size}')

컬럼 인덱스 확인 : 
Index(['id', 'document', 'label'], dtype='object')
--------------------------------------------------------------------------------
첫 번째 컬럼의 이름 : id
--------------------------------------------------------------------------------
행 인덱스 확인 : RangeIndex(start=0, stop=150000, step=1)
--------------------------------------------------------------------------------
값(데이터) 추출 : 
[[9976970 '아 더빙.. 진짜 짜증나네요 목소리' 0]
 [3819312 '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나' 1]
 [10265843 '너무재밓었다그래서보는것을추천한다' 0]
 ...
 [9311800 '이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?' 0]
 [2376369 '청춘 영화의 최고봉.방황과 우울했던 날들의 자화상' 1]
 [9619869 '한국 영화 최초로 수간하는 내용이 담긴 영화' 0]]
--------------------------------------------------------------------------------
데이터프레임의 모양(구조) 확인 : (150000, 3)
--------------------------------------------------------------------------------
데이터프레임의 성분 원소 개수 확인 : 450000


## 인덱싱

In [ ]:
### 특정 컬럼 1개 추출 → 인덱싱

# 문자열 인덱스를 이용
result = df2.loc[:, 'document']
print(f'특정 컬럼 1개를 인덱싱한 결과 : \n{result}')

특정 컬럼 1개를 인덱싱한 결과 : 
0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...                        
149995                                  인간이 문제지.. 소는 뭔죄인가..
149996                                        평점이 너무 낮아서...
149997                      이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149998                          청춘 영화의 최고봉.방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 150000, dtype: object


In [ ]:
### 컬럼 1개씩 여러 개를 동시에 추출 → fancy 인덱싱

# 전체 컬럼 → 'document', 'label' 컬럼 2개 인덱싱
result = df2.loc[:, ['document', 'label']]
print(f'fancy 인덱싱의 결과 : \n{result}')

fancy 인덱싱의 결과 : 
                                                 document  label
0                                     아 더빙.. 진짜 짜증나네요 목소리      0
1                       흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2                                       너무재밓었다그래서보는것을추천한다      0
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4       사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...                                                   ...    ...
149995                                인간이 문제지.. 소는 뭔죄인가..      0
149996                                      평점이 너무 낮아서...      1
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 2 columns]


## 누락 데이터 확인

In [ ]:
### 전체 데이터프레임에 대한 누락 데이터 확인

# isnull() 함수 사용
df_bool = df2.isnull()
print(f'각 컬럼에 대한 누락 여부 확인 \n{df_bool}')

print('-'*80)

# isnull().sum() 함수 사용
num_nulls = df2.isnull().sum()
print(f'각 컬럼별 누락 데이터의 수 확인 : \n{num_nulls}')

각 컬럼에 대한 누락 여부 확인 
           id  document  label
0       False     False  False
1       False     False  False
2       False     False  False
3       False     False  False
4       False     False  False
...       ...       ...    ...
149995  False     False  False
149996  False     False  False
149997  False     False  False
149998  False     False  False
149999  False     False  False

[150000 rows x 3 columns]
--------------------------------------------------------------------------------
각 컬럼별 누락 데이터의 수 확인 : 
id          0
document    5
label       0
dtype: int64


In [ ]:
### 특정 컬럼에 대한 누락 데이터 확인

# isull() 함수 사용
se_bool = df2.loc[:,'document'].isnull()
# df2.document.isnull()
print(f'document 컬럼에 대한 누락 여부 확인 : \n{se_bool}')

print('-'*80)

# isnulll().sum()
num = df2.loc[:,'document'].isnull().sum()
print(f'document 컬럼에 대한 누락 데이터의 수 = {num}개')

document 컬럼에 대한 누락 여부 확인 : 
0         False
1         False
2         False
3         False
4         False
          ...  
149995    False
149996    False
149997    False
149998    False
149999    False
Name: document, Length: 150000, dtype: bool
--------------------------------------------------------------------------------
document 컬럼에 대한 누락 데이터의 수 = 5개


In [ ]:
### 보충 : boolean 자료형 데이터의 특성

# 연산 : True → 1, False → 0
sum = True + True + False
print(f'블리언 자료형의 덧셈 연산의 결과 : {sum}')

블리언 자료형의 덧셈 연산의 결과 : 2


## 누락 데이터 처리

In [ ]:
### dropna(subset=[], inplace, ignore_index=True ) 함수 사용
df_cleaned = df2.dropna(ignore_index=True)

# 결과 확인
print(f'누락 데이터 제거 전 데이터 프레임 : \n{df2}')
print('-'*80)
print(f'누락 데이터 제거 후 데이터 프레임 : \n{df_cleaned}')

누락 데이터 제거 전 데이터 프레임 : 
              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]
--------------------------------------------------